
rss_news_provider:
  sources:
    - "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada"
    - "http://ep00.epimg.net/rss/tags/ultimas_noticias.xml"
    - "https://www.lavanguardia.com/rss/home.xml"
    - "http://api2.rtve.es/rss/temas_noticias.xml"
    - "https://e00-elmundo.uecdn.es/elmundo/rss/espana.xml"
    - "https://okdiario.com/feed"
    - "https://e00-expansion.uecdn.es/rss/portada.xml"
    - "https://www.abc.es/rss/feeds/abc_ultima.xml"
    - "https://www.abc.es/rss/feeds/abcPortada.xml"
    - "https://periodistadigital.webnode.es/rss/all.xml"
  period: 5

news_cleaner:
  ttl: 1440 #24H
  period: 30

latest_news_count: 30